name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - pandas <2
  - bqplot
  - ipywidgets==8.0.7
  - numpy==1.25.1
  - seaborn==0.12.2

